import 'package:first_app/helpers/IconFontHelper.dart';
import 'package:first_app/models/category.dart';
import 'package:first_app/models/onboardingcontent.dart';
import 'package:first_app/models/subcategory.dart';

import 'appcolors.dart';

class utils {
  static List<OnboardingContent> getOnboarding() {
    return [
      OnboardingContent(
        message: 'No More Running late for your bus and no more morning chaos',
        img: 'chaos'
      ),
      OnboardingContent(
        message: 'No more Calls or Messages for the location of your Bus Stop',
        img: 'bus'
      ),
      OnboardingContent(
        message: 'Have all the details to make your journey Happy!',
        img: 'bus 1'
      )
    ];
  }

  static List<Category> getMockedCategories() {
    return [
      Category(
        color: AppColors.MAIN_COLOR,
        name: "BH-1",
        imgname: "bhiwadi",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.MAIN_COLOR,
            name: "Honda Chowk",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MAIN_COLOR,
            name: "Ashiyana Town",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MAIN_COLOR,
            name: "Ashiyana Angan",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MAIN_COLOR,
            name: "Skipper Cell",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MAIN_COLOR,
            name: "Rajashtan Border",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MAIN_COLOR,
            name: "Tauru",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MAIN_COLOR,
            name: "Sohna Chowk",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
      Category(
        color: AppColors.FRUITS,
        name: "C-1",
        imgname: "GK",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.FRUITS,
            name: "Lajpat Nagar",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.FRUITS,
            name: "Nehru Stadium",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.FRUITS,
            name: "Kotla",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.FRUITS,
            name: "Chanakyapuri Leela Hotel",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.FRUITS,
            name: "Dhaula Kuan",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.FRUITS,
            name: "Subroto Park",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.FRUITS,
            name: "Jhareda Bus Stop",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.FRUITS,
            name: "Mahipalpur",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.MEATS,
        name: "DW-1",
        imgname: "DW1",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.MEATS,
            name: "CRPF Camp",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Subash Nagar Metro",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Rajouri Garden",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Subhash Nagar",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Beri Bagh",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Hari Nagar",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Bharti College",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Janak Puri",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Sagar Pur",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Dabhri Mod",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Sita Puri",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Dwarka Sector-1",
            imgName: "11",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Palam Colony",
            imgName: "12",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Ramfal Chowk(red light)",
            imgName: "13",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.MEATS,
        name: "DW-2",
        imgname: "DW2",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.MEATS,
            name: "VikasPuri",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Uttam Nagar West",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Tilak Pul",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Sai Baba Temple",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Dwarka Mod",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Dwarka Sector-3 & 4",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "DPS Matiyala",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Raja Puri",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Dwarka Sector-6 & 10",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Dwarka Sector-5",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "SamalkhaQueens Valley Sec-8",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.MEATS,
            name: "Samalkha",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
      Category(
        color: AppColors.VEGS,
        name: "E-1",
        imgname: "E1",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.VEGS,
            name: "Nirman Vihar",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Mother Dairy",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Lajpat Nagar",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Moolchand Flyover",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Kotla Red Light",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Uday Park",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Gulmoher Park",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Hauz Khas",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Arjini",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Lado Sarai",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Qutub Minar",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Andehri Mod",
            imgName: "11",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.VEGS,
            name: "Arjangarh",
            imgName: "12",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.SEEDS,
        name: "F-1",
        imgname: "F1",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.SEEDS,
            name: "RPS Gate No.1",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Sarai Chowk",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Baderpur Border",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "NHPC",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "IP Colony",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Sec 29 Fruit Market",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Sec 17 CNG Pump",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Sec 14 Bypass Redlight",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Green Dora Sec 81",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "BPTP Redlight Bridge",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Milan Sweet",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Sector 3",
            imgName: "11",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Gudyar Chowk NH2",
            imgName: "12",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Hardware Chowk",
            imgName: "13",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Piyali Chowk",
            imgName: "14",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Maszid mod",
            imgName: "15",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Sainik Colony Redlight",
            imgName: "16",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SEEDS,
            name: "Gwal Phari",
            imgName: "17",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
      Category(
        color: AppColors.PASTRIES,
        name: "G-1",
        imgname: "G1",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sector 14",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Railway Road",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Shivaji Nagar",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "New Colony",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sector 4",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sec-4 & 7 Road",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sec 9 ASI",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sec-4 & 9 Road(a)",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Basai",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Alpine Public School",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sector 10",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Hero Honda chowk",
            imgName: "11",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Subhash Chowk",
            imgName: "12",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.PASTRIES,
        name: "G-2",
        imgname: "G2",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Nathu Pur",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "DLF Phase-3",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Ghata",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Railway Vihar",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Kendriya Vihar",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Home Kom Bazar",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Ghata Redlight Point",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sec 56 Redlight",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
      Category(
        color: AppColors.PASTRIES,
        name: "G-3",
        imgname: "G3",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Serhol",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Mata Mandir",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Mata Mandir Petrol pump",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Prakash Puri",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sec 5 Gol Chakar",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sec 5 Petrol Pump",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Krishna Murti Chowk",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Geeta Properties",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sec 23 Gate No 1",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Chauma Shiv Mandir",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Ansal Chowk",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Kataria Chowk",
            imgName: "11",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Sector 17",
            imgName: "12",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.PASTRIES,
            name: "Rajiv Chowk",
            imgName: "13",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.SPICES,
        name: "H-1",
        imgname: "H",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.SPICES,
            name: "Huda City(metro)",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Fortis Out Gate",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "CNG Pump Sec-44",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Gold Shop",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Kanhai Mode",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Ardee City gate No-3",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Amity School",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "May Field Garden",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Park Hospital",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "South City II",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "O-Max",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Sec-56 Redlight Point",
            imgName: "11",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Badshapur",
            imgName: "12",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
      Category(
        color: AppColors.SPICES,
        name: "H-2",
        imgname: "H",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.SPICES,
            name: "HUDA City(Metro)",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Sec-31 Redlight",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Sector 40",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Cyber Park",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Sector 46A",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Sector 46B",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "BakhTawar Chowk",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Subash chowk",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Sec 56 Redlight",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Badshapur",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.SPICES,
        name: "H-3",
        imgname: "H",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.SPICES,
            name: "Huda City(Metro)",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Sec 40,46 Redlight",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Bakhtawar Chowk",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Subash Chowk",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Vatika Redlight",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.SPICES,
        name: "H-4",
        imgname: "H",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.SPICES,
            name: "Huda City(Metro)",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Sec 40,46 Redlight",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Bakhtawar Chowk",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Subash Chowk",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "Vatika Redlight",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.SPICES,
            name: "BadshaPur",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
      Category(
        color: AppColors.N1,
        name: "N-1",
        imgname: "N1",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.N1,
            name: "Vikaspuri Aggarwal",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Uttam Nagar East",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Nawada Metro",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Dwarka Metro",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Sai Baba Temple",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Najafgarh",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "BDO Roshanpura",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Deenpur",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Jhatikra More",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Chawala",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.N1,
            name: "Samalkha",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.R1,
        name: "R-1",
        imgname: "R1",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.R1,
            name: "Rajiv Chowk",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Islampur Village",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Sec 56 Redlight",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Badshapur",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Bhondsi Bus Stop",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Ghamdoj Bus Stop",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Alipur Main Road",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
      Category(
        color: AppColors.R1,
        name: "R-2",
        imgname: "R2",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.R1,
            name: "Rajiv Chowk",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Islampur Village",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Sec 56 Redlight",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Badshapur",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Bhondsi Bus Stop",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Ghamdoj Bus Stop",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.R1,
            name: "Alipur Main Road",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
      Category(
        color: AppColors.S1,
        name: "S-1",
        imgname: "S1",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.S1,
            name: "Govind Puri",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "Jamia",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "Nehru Place",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "Kailash Place",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "GK-1",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "RK Puram",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "Munirka",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "Vasant Vihar",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "Vasant Kunj",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "Fortis",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.S1,
            name: "Chattarpur",
            imgName: "10",
            icon: IconFontHelper.LOGO,
          ),
        ],
      ),
      Category(
        color: AppColors.W1,
        name: "W-1",
        imgname: "W1",
        icon: IconFontHelper.LOGO,
        subcategories: [
          SubCategory(
            color: AppColors.W1,
            name: "Meera Bagh",
            imgName: "0",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Peeragarhi",
            imgName: "1",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Madhuban Chowk",
            imgName: "2",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Pitampura",
            imgName: "3",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Wazirpur Depo",
            imgName: "4",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Punjabi Bagh",
            imgName: "5",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Rajori Garden",
            imgName: "6",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Nariana",
            imgName: "7",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Dhaulan Kuan",
            imgName: "8",
            icon: IconFontHelper.LOGO,
          ),
          SubCategory(
            color: AppColors.W1,
            name: "Mahipalpur",
            imgName: "9",
            icon: IconFontHelper.LOGO,
          )
        ],
      ),
    ];
  }
}
